### ISSUE TITLE
Question about approving ads in the test environment

### ISSUE THREAD

**Issue by 2food** [navikt/pam-import-api#25]
How and when are posted ads approved in the test environment? 
Is this done manually as in production, or is it automatic?

I'm asking because I would like to see what a posted ad looks like in the test environment, and I can't view it before its status is `PUBLISHED`

**Comment by tuantrannav** [comment]
Hi!

In test environment we will approved the ads as soon as we get them. Please let us know if you dont see them approved yet. Sadly because of another firewall problem, it is not possible to preview the ads yet in test environment. However In production you will be able to see it by following the url in ad status receipt. We are working on improving test environment and soon all limitations and firewall problems in test envionment will be removed.

**Comment by 2food** [comment]
@tuantrannav ah, okay. Thanks :+1:
